import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import Head from "next/head";

export default function Home() {

  

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center">
        <div className="flex w-full max-w-sm items-center space-x-2">
          <Input type="text" placeholder="new item" />
          <Button type="submit">Add</Button>
        </div>
      </div>
    </>
  );
}
