import Head from "next/head";
import { AddTask } from "~/components/AddTask";
import { DataProvider } from "~/components/DataProvider";
import Header from "~/components/Header";
import { TaskList } from "~/components/TaskList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DataProvider>
        <Header />
        <div className="flex h-fit flex-col items-center justify-center gap-2 p-4">
          <div className="text-center text-xl "> TODOs</div>
          <TaskList />
          <AddTask />
        </div>
      </DataProvider>
    </>
  );
}
