import Head from "next/head";
import { AddTask } from "~/components/AddTask";
import { TaskList } from "~/components/TaskList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen flex-col gap-2 items-center justify-center">
        <TaskList />
        <AddTask />
      </div>
    </>
  );
}
